### PR TITLE
Applied fixes from StyleCI

### PR DESCRIPTION
**Pull request by devmachine321**
This pull request applies code style fixes from an analysis carried out by [StyleCI](https://styleci.io).

---

For more information, click [here](https://styleci.io/analyses/z9xn0P).

### CODE REVIEW

**Comment by bustapaladin** [comment]
@devmachine321 hey

**Comment by ghost** [comment]
Hey have you committed on the project yet. Were working on the code, right now.

I think it is almost done.

**Comment by bustapaladin** [comment]
Well are you the guy from Discord?

**Comment by ghost** [comment]
Yes
I am

**Comment by ghost** [comment]
🎯

**Comment by bustapaladin** [comment]
@alwaysontop617 so what happened on Discord? You kind of went a bit crazy? Never gonna get that revision plugin to work huh?  :(

**Pull request merged**
